services:
  - type: web
    name: team-map
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt && npm install && npm run build
    startCommand: gunicorn wsgi:app
    envVars:
      - key: GIPHY_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.1